# TASK 1 FIRST VARIABLE
x = 5

#QUESTION
# WHAT IS THE OUTPUT? 5
#WHAT IS THE VALUE OF STORED IN VARIABLE X? 5
# WHAT HAPPENS IF YOU CHANGE 5 TO 10? THE VALUE OF X BECOMES 10, AND THE OUTPUT WILL ALSO CHANGE TO 10

# TASK 2 STRING VARIABLE
name = "Jamella Mae"
print(name)

#TASK 3 MULTIPLE VARIABLES
x = 5
y = "John"
print(x)
print(y)
#QUESTION 
#WHICH VARIABLE STORES A NUMBER? THE VARIABLE OF X STORES NUMBER
#WHICH VARIABLES STORE TEXT? THE VARIABLE OF Y STORES TEXT

# TASK 4 CHANGING VALUES
x = 4
x = "Sally"
print(x)
#QUESTION
#WHAT IS THE OUTPUT? THE OUTPUT IS "Sally"
#WHY DID THE NUMBER DISAPPEAR? THE NUMBER DISAPPEARED BECAUSE 
#THE VALUE OF X WAS CHANGED TO A STRING, SO THE PREVIOUS VALUE OF 4 IS REPLACED BY "Sally"

#TASK 5 OVERWRITING VARIABLES
age = 18
print(age)
age = 19
print(age)